---
# custom image details
name: ublue-gnome
description: Fedora Silverblue base OS image >> Universal Blue rebased OS image + GNOME desktop environment + CachyOS kernel

# base image
base-image: ghcr.io/ublue-os/base-main
image-version: latest

# module configuration, executed in order
modules:
  - type: script
    
    # run scripts
    scripts:
    - kernel-cachyos.sh

  - type: dnf
  
    # install packages
    group-install:
      with-optional: false
      packages:
        - gnome-desktop
        
    # install system packages    
    install:
      packages:
        - fastfetch
        - fish
        
    # remove packages
    remove:
      packages:
        - nvtop
        - htop
        - firefox
        - firefox-langpacks

  - type: systemd
    
    # enable systemd services
    system:
      enabled:
        - gdm

  # this sets up the proper policy and signing files for signed images to work fully
  - type: signing
